/**
 * RealPullRequestService - Real implementation for Pull Request operations
 * Creates actual pull requests on GitHub and links them to Azure DevOps work items
 */

import { Octokit } from '@octokit/rest';
import { 
  IPullRequestService, 
  IPullRequestCreationResult, 
  IPullRequestUpdateResult,
  IPullRequestInfo 
} from '../../models/git';
import { IAzureDevOpsService } from '../azure/azureDevOpsService';
import { IEnrichedWorkItem } from '../../models/workItem';

export class RealPullRequestService implements IPullRequestService {
  private octokit: Octokit;
  private owner: string;
  private repo: string;
  private defaultBranch: string;
  private azureDevOpsService: IAzureDevOpsService;

  constructor(
    githubToken: string,
    owner: string,
    repo: string,
    defaultBranch: string = 'main',
    azureDevOpsService: IAzureDevOpsService
  ) {
    this.octokit = new Octokit({
      auth: githubToken,
    });
    this.owner = owner;
    this.repo = repo;
    this.defaultBranch = defaultBranch;
    this.azureDevOpsService = azureDevOpsService;
  }

  async createPullRequest(
    sourceBranch: string,
    title: string,
    description: string,
    workItem: IEnrichedWorkItem,
    reviewers?: string[]
  ): Promise<IPullRequestCreationResult> {
    try {
      // Create the pull request
      const response = await this.octokit.rest.pulls.create({
        owner: this.owner,
        repo: this.repo,
        title,
        body: this.formatPullRequestDescription(description, workItem),
        head: sourceBranch,
        base: this.defaultBranch,
      });

      const pullRequest = response.data;

      // Add reviewers if specified
      if (reviewers && reviewers.length > 0) {
        await this.octokit.rest.pulls.requestReviewers({
          owner: this.owner,
          repo: this.repo,
          pull_number: pullRequest.number,
          reviewers,
        });
      }

      // Link to Azure DevOps work item
      await this.azureDevOpsService.linkPullRequestToWorkItem(
        workItem.id,
        pullRequest.number,
        this.repo
      );

      return {
        success: true,
        pullRequestId: pullRequest.number,
        pullRequestUrl: pullRequest.html_url,
        message: 'Pull request created successfully'
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        message: 'Failed to create pull request'
      };
    }
  }

  async updatePullRequest(
    pullRequestId: number,
    title?: string,
    description?: string
  ): Promise<IPullRequestUpdateResult> {
    try {
      const updateData: any = {};
      if (title) updateData.title = title;
      if (description) updateData.body = description;

      const response = await this.octokit.rest.pulls.update({
        owner: this.owner,
        repo: this.repo,
        pull_number: pullRequestId,
        ...updateData,
      });

      return {
        success: true,
        pullRequestUrl: response.data.html_url,
        message: 'Pull request updated successfully'
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred',
        message: 'Failed to update pull request'
      };
    }
  }

  async getPullRequestInfo(pullRequestId: number): Promise<IPullRequestInfo | null> {
    try {
      const response = await this.octokit.rest.pulls.get({
        owner: this.owner,
        repo: this.repo,
        pull_number: pullRequestId,
      });

      const pr = response.data;
      return {
        id: pr.number,
        title: pr.title,
        description: pr.body || '',
        sourceBranch: pr.head.ref,
        targetBranch: pr.base.ref,
        state: pr.state,
        url: pr.html_url,
        createdAt: new Date(pr.created_at),
        updatedAt: new Date(pr.updated_at)
      };
    } catch (error) {
      return null;
    }
  }

  private formatPullRequestDescription(description: string, workItem: IEnrichedWorkItem): string {
    return `${description}

## Work Item Details
- **ID**: ${workItem.id}
- **Type**: ${workItem.type}
- **Title**: ${workItem.title}
- **Area Path**: ${workItem.areaPath}
- **Iteration**: ${workItem.iterationPath}

## Description
${workItem.description || 'No description provided'}

${workItem.acceptanceCriteria ? `## Acceptance Criteria\n${workItem.acceptanceCriteria}` : ''}

${workItem.reproductionSteps ? `## Reproduction Steps\n${workItem.reproductionSteps}` : ''}

---
*This pull request was automatically generated by Redimento Code Generator*`;
  }
}